### ISSUE TITLE
tab Issue in iPad Air 2 after changing the position tabBarViewPosition to bottom 

### ISSUE THREAD

**Issue by dipak018** [hemangshah/HHTabBarView#7] opened 2018-08-16 00:10 UTC
HI Hemang,

After changing the tabBarViewPosition to bottom, if you tap on any tab or on the screen the first tab will be selected.

Regards,
Dipak

**Comment by hemangshah** [comment] 2018-08-16 04:12
Hi @dipak018 , sorry to hear about that issue with you. Can you please update your problem with more details? And how to reproduce?

**Comment by dipak018** [comment] 2018-08-16 08:12
Hi Hemang,

I am facing the issue on iPad Air 2 Simulatore not sure about the device.

Steps to reproduce the issue -  
1. Added 5 tabs

**Comment by dipak018** [comment] 2018-08-16 08:18
it's weird, the issue dose not occur all the time.

The issue is - when you select any tab it will automatically select first tab and second time selection that tab will be selected.

Consider, we have - Tab1, Tab2, Tab3, Tab4, Tab5
so if I am selecting Tab2 it will select Tab1 again you select Tab2 then only it will be selected.

**Comment by hemangshah** [comment] 2018-08-16 11:08
Okay, I will check and let you know. Meantime, if you will any updates please feel free to update this issue with more information.

**Comment by hemangshah** [comment] 2018-08-17 07:54
@dipak018 , I am not able to reproduce this issue, can you please send a sample code so I can check?

**Comment by dipak018** [comment] 2018-08-17 15:36
@hemangshah Thank you for the support.

When i was getting the issue at the same time I tested on the sample provided by you. And it was happening for that too.

Even I am not able to reproduce it again, If i find it, I will update you on the same.

**Comment by hemangshah** [comment] 2018-08-19 05:04
@dipak018, I checked it in iPad Air 2 and it is still not happening at my end. Since you have checked the sample code I don't require your `HHTabBarView` configurations (believing you have not changed it). A property `defaultIndex` is helpful to set the default index to show in the tab bar.

**Comment by hemangshah** [comment] 2018-08-19 05:05
If you can share a video showing this bug which may help to get an idea, otherwise I am not able to reproduce it at my end.

**Comment by hemangshah** [comment] 2018-08-19 05:12
We can also connect via Skype, please send me your skype id to my email. You can find the email in my profile page. For now, closing this issue.

**Closed by hemangshah** 2018-08-19 05:12 UTC
